### ISSUE TITLE
Week03-01 문제 질문 [GUI]

### ISSUE THREAD

**Issue by CheHyeonYeong** [beagglechung/2023_JAVA#1]
```
JLabel lblNewLabel = new JLabel("이름");
		lblNewLabel.setBounds(36, 45, 151, 15);
		contentPane.add(lblNewLabel);
```

교수님 여기서 setBounds는 무슨 메소드인지 알려주실 수 있나요?

**Comment by beagglechung** [comment]
안녕하세요
각각의 컴포넌트의 위치를 정하기 위해서 사용한 메소드 입니다
뒤에 숫자는 위치에 해당하는 절대 값입니다

코드는 여러가지 방법이 있으니 참고만 하세요

정혜진

2023년 9월 22일 (금) 오후 4:40, Hyeon-Yeong Chae ***@***.***>님이 작성:

**Comment by CheHyeonYeong** [comment]
안녕하세요 정혜진 교수님 심화객체프로그래밍을 수강중인 수강생입니다. 친절히 알려주셔서 감사합니다 :D !

**Comment by beagglechung** [comment]
넹❤️ 즐거운 주말 보내용!



2023년 9월 22일 (금) 오후 5:49, Hyeon-Yeong Chae ***@***.***>님이 작성:
